-- Tabela USERS
CREATE TABLE USERS (
    USERNAME VARCHAR(100) NOT NULL PRIMARY KEY,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

-- Tabela MOVIES
CREATE TABLE MOVIES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DIRECTOR VARCHAR(255) NOT NULL,
    RELEASEDATE DATE NOT NULL,
    VOTEAVERAGE VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    CONSTRAINT fk_movies_users
        FOREIGN KEY (USER_ID)
            REFERENCES USERS(USERNAME)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
    );

CREATE UNIQUE INDEX IF NOT EXISTS IX_AUTH_USERNAME ON AUTHORITIES(USERNAME, AUTHORITY);
